services:
  db:
    image: postgres:14-alpine3.21
    volumes:
      - pgdata:/var/lib/postgresql/data
    environment:
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=inthw
  backend:
    build: .
    volumes:
      - .:/inthw
    ports:
      - '8000:8000'
    depends_on:
      - db
volumes:
  pgdata:
