# Get clients
GET http://localhost:8000/api/v1/clients/ HTTP/1.1
Authorization: Bearer

###
# Get client by id
GET http://localhost:8000/api/v1/clients/1 HTTP/1.1
Authorization: Bearer 

###
# Get projects
GET http://localhost:8000/api/v1/projects/ HTTP/1.1
Authorization: Bearer
Accept: application/json

###
# Get objects
GET http://localhost:8000/api/v1/objects/ HTTP/1.1
Authorization: Bearer
Accept: application/json

###
# Get object by id
GET http://localhost:8000/api/v1/objects/1 HTTP/1.1
Authorization: Bearer
Accept: application/json

###
# Get persons
GET http://localhost:8000/api/v1/persons/ HTTP/1.1
Authorization: Bearer
Accept: application/json

###
# Get person by id
GET http://localhost:8000/api/v1/persons/1 HTTP/1.1
Authorization: Bearer
Accept: application/json

###
# Get data points
GET http://localhost:8000/api/v1/datapoints/ HTTP/1.1
Authorization: Bearer
Accept: application/json

###
# Get data point by id
GET http://localhost:8000/api/v1/datapoints/1 HTTP/1.1
Authorization: Bearer
Accept: application/json

###
# Create a client
POST http://localhost:8000/api/v1/clients/ HTTP/1.1
Authorization: Bearer 
Accept: application/json
Content-Type: application/json

{
    "user": 5
}

###
# Create a project
POST http://localhost:8000/api/v1/projects/ HTTP/1.1
Authorization: Bearer
Accept: application/json
Content-Type: application/json

{
    "label": "",
    "client": 
}

###
# Create a object
POST http://localhost:8000/api/v1/objects/ HTTP/1.1
Authorization: Bearer
Accept: application/json
Content-Type: application/json

{
    "label": "",
    "project": 3,
    "responsible_persons": [],
    "data_points": []
}

###
# Create a person
POST http://localhost:8000/api/v1/persons/ HTTP/1.1
Authorization: Bearer
Accept: application/json
Content-Type: application/json

{
    "first_name": "",
    "last_name": ""
}

###
# Create a data point
POST http://localhost:8000/api/v1/datapoints/ HTTP/1.1
Authorization: Bearer
Accept: application/json
Content-Type: application/json

{
    "label": ""
}

###
# Retrieve JWT access and refresh tokens
POST http://localhost:8000/api/token/ HTTP/1.1
Content-Type: application/json

{
    "username": "admin",
    "password": "admin"
}

###
# Retrieve JWT access token with refresh token
POST http://localhost:8000/api/token/refresh/ HTTP/1.1
Content-Type: application/json

{
    "refresh": ""
}
